### ISSUE TITLE
No Powercycle after state WarmUp

### ISSUE THREAD

**Issue by MiJo112** [amosyuen/ha-epson-projector-link#132]
When the projector switches from WarmUp to On Start mode, the integration does not notice this and cannot be switched off with the integration.
After a reload of the integration, the status is correct and the control also works until the next warm-up.
There is an error in the log, I think it is related to this.
Traceback (most recent call last):
  File "/config/custom_components/epson_projector_link/projector/projector.py", line 286, in _listen
    await self._handle_imevent(value)
  File "/config/custom_components/epson_projector_link/projector/projector.py", line 330, in _handle_imevent
    warning_bitmask = hex_string_to_int(parts[2])
Log:
[home-assistant_2024-12-11T11-37-25.009Z.log](https://github.com/user-attachments/files/18111933/home-assistant_2024-12-11T11-37-25.009Z.log)

**Comment by amosyuen** [comment]
There was a bug in the code that is fixed in https://github.com/amosyuen/ha-epson-projector-link/commit/6f4b235b6e23699e3dca33c06a2bd4f71a9f07a4
